runtime: python39
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3.9

handlers:
  - url: /static
    static_dir: frontend/build/static

  - url: /.*
    script: auto

env_variables:
  IS_DEV: false